import type { Metadata } from 'next';
import './globals.css';
import { MicrophoneContextProvider } from './components/microphone/microphoneContextProvider';
import { DeepgramContextProvider } from './components/transcription/deepgramContextProvider';
import { FontAwesomeInstallScript } from '@/app/components/fontawesome/fontAwesomeScript';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Very Debate</title>
        <FontAwesomeInstallScript />
      </head>
      <body className={`antialiased`}>
        <MicrophoneContextProvider>
          <DeepgramContextProvider>{children}</DeepgramContextProvider>
        </MicrophoneContextProvider>
      </body>
    </html>
  );
}
