import type { Metadata } from 'next';
import './globals.css';
import { FontAwesomeInstallScript } from '@/app/components/fontawesome/fontAwesomeScript';
import { ProviderPyramid } from '@/app/components/providerPyramid';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Very Debate</title>
        <FontAwesomeInstallScript />
      </head>
      <body className={`antialiased`}>
        <ProviderPyramid>{children}</ProviderPyramid>
      </body>
    </html>
  );
}
